### ISSUE TITLE
ADS-B "daily report" from my Raspberry Pi Receiver 

### ISSUE THREAD

**Issue by Mike-D-424** [eastham/adsb_actions#22]
I wish to find a magic way for my existing ADS-B feed to create and (preferably e-mail me) a daily report including aircraft ID, speed, heading, date, time, altitude, etc. of any aircraft lower than 1000 ft that my device receives.  

The reason I want this is I am tired of helicopters making my house shake since I live under their approach to a local airport.  

I am not at all a coding or pi expert, therefore the simpler and easier-to-implement solution is preferred.  

Thank you,  Michael

**Comment by eastham** [comment]
This will work with a rule something like the following.  It only prints when an aircraft matches, you will have to take it from there:

```
print_low_aircraft:
  conditions:
    max_alt: 1000
    latlongring: [5, lat.xxxx, long.xxx]  # 5 nm ring around your house specified in the lat and long fields
    cooldown: 10 # only print every 10 minutes, presumably long enough for the aircraft to leave the ring

```
